name: Barrage
main: net.moosecraft.Barrage.Barrage
version: 3.0
commands:
   barrage:
      description: Upgrade your arsenal with a variety of specialty arrows
      usage: "left click your bow to change arrow types"